Fix TypeError: slice indices must be integers
After Port to Python 3, the datastore did report a traceback on query
indicating that the limit or offset were not integer;

dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/carquinyol/datastore.py", line 425, in _find_all
    uids = uids[offset:offset + limit]
TypeError: slice indices must be integers or None or have an __index__ method

Caused by Python 3 division operator now yielding float.

Fixes https://github.com/sugarlabs/sugar/issues/862
Fixes https://github.com/sugarlabs/sugar/issues/863

Not tested.