Fix Traceback when connecting to a network for the first time
When connecting to a network that we don't have settings for yet, the following
Traceback was logged:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 586, in msg_reply_handler
    reply_handler(*message.get_args_list(**get_args_opts))
TypeError: _activate_reply_cb() takes exactly 1 argument (2 given)

This is because the same set of callbacks was used for both
ActivateConnection() and AddAndActivateConnection() even though they return
different sets of values.

Signed-off-by: Sascha Silbe <silbe@activitycentral.com>
Reviewed-by: Daniel Drake <dsd@laptop.org>