Fix AttributeError: 'str' object has no attribute 'decode'
After Port to Python 3, the display name for a WirelessNetworkView is
already unicode, so no need to decode.

Fixes https://github.com/sugarlabs/sugar/issues/861

Not tested.