Fix TypeError when copying to Documents
Journal copy to Documents does fail silently, leaving a temporary file
in the Documents directory, and may log a traceback;

Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/journal/model.py", line 859, in _write_entry_on_external_device
    os.write(fh, metadata_json)
TypeError: a bytes-like object is required, not 'str'

Fixes https://github.com/sugarlabs/sugar/issues/865