Localize unnamed arguments with named arguments and mapping - invalid syntax 2
During install of an Ubuntu package;

  File "/usr/lib/python2.7/dist-packages/jarabe/controlpanel/cmd.py", line 102
    % ('key': key, 'module': module))
            ^
SyntaxError: invalid syntax

Regression introduced by e4e2d87.

Also removed double translation, and a message that will never be
translated.