Fix jarabe.model.screenshot.IOError
Screenshot does not work, no journal object created, logs contain;

Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/model/screenshot.py", line 118, in _get_preview_data
    preview_surface.write_to_png(preview_str)
jarabe.model.screenshot.IOError: error while writing to output stream

Caused by writing binary data into a Unicode-only memory file.

Another regression from aa18879 ("Port to Python 3").

Fixes https://github.com/sugarlabs/sugar/issues/857
Fixes https://github.com/sugarlabs/sugar/issues/867