Fix AttributeError in modem control panel
After opening the Modem control panel in My Settings, logs contain;

Traceback (most recent call last):
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 279, in __init__
    country_code, provider_name, plan_idx = self._get_initial_config()
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 332, in _get_initial_config
    provider_name = provider_name.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

As get_string returns a string, there's no need to decode.

Regression introduced in aa18879 ("Port to Python 3")

Signed-off-by: James Cameron <quozl@laptop.org>