Work in progress - fix text clipping cannot be removed from Frame
Text clipping remains after request to remove.  Logs contain

1565770157.805620 WARNING root: no data for selection target MULTIPLE.
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/frame/clipboardtray.py", line 117, in _object_added_cb
    objects_to_delete = self.get_children()[:-self.MAX_ITEMS]
TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/frame/clipboardicon.py", line 155, in _object_state_changed_cb
    if self._current_percent < 100 and cb_object.get_percent() == 100:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/jarabe/frame/clipboardicon.py", line 155, in _object_state_changed_cb
    if self._current_percent < 100 and cb_object.get_percent() == 100:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
1565770157.814280 WARNING root: no data for selection target NULL.