Fixed traceback: Keyerror 'mountpoints' in query['mountpoints']
for ProjectView the query in the list-view has no key for 'mountpoints'.
Hence after adding new entry and refreshing the view in Journal following traceback is shown in log
  File /home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/listview.py, line 238, in _is_new_item_visible
    if self._query['mountpoints'] == ['/']:
KeyError: 'mountpoints'

Possible fix:
if not self._query.get('mountpoints',None):
   return None