Fix AttributeError raised by choosing Favorites View
t is reproduced by choosing Favorites View - Random View from the toolbar in the Home View.
Impact is that the favourites view disappears and is empty.

Fixes #923
Regression made in aa18879#diff-685d653cc9490267e474dabc5c40b108R249
get_bundle_id always returns a str, encode it
md5 hash function accepts sequence of bytes

Reported by - Shaan Subbaiah <shaansubbaiah.cs18@bmsce.ac.in>
Traceback (most recent call last):
  File /usr/lib/python3/dist-packages/jarabe/desktop/viewcontainer.py, line 69, in do_size_allocate
    self._layout.allocate_children(allocation, self._children)
  File /usr/lib/python3/dist-packages/jarabe/desktop/favoriteslayout.py, line 250, in allocate_children
    name_hash = hashlib.md5(child.get_bundle_id().decode())
AttributeError: 'str' object has no attribute 'decode'