Fix AttributeError in Random Favorites View
After selecting the Random view in Favorites, the view is empty, and
logs contain;

Traceback (most recent call last):
  File /usr/lib/python3/dist-packages/jarabe/desktop/favoriteslayout.py, line 250, in allocate_children
    name_hash = hashlib.md5(child.get_bundle_id().decode())
AttributeError: 'str' object has no attribute 'decode'

get_bundle_id returns a string, hashlib.md5 requires bytes, so convert
from string to bytes.

Fixes https://github.com/sugarlabs/sugar/issues/923

Regression in aa18879 ("Port to Python 3").

Reported by: Shaan Subbaiah <shaansubbaiah.cs18@bmsce.ac.in>
Signed-off-by: James Cameron <quozl@laptop.org>