Fix AttributeError while opening modem control panel
https://github.com/sugarlabs/sugar/blob/d59b62a5f1db8c1e1ecb7ccbbcc8b85163290908/extensions/cpsection/modemconfiguration/model.py#L318 already returns a 'str' object, there is no need to decode from 'UTF-8'.
Regression in aa18879#diff-faa2d318ce1ef21991d9ca1c6fa958ac
Fixes following Erros:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 459, in __select_option_cb
    self.show_section_view(option)
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 313, in show_section_view
    self._section_view = view_class(model,
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/view.py", line 125, in __init__
    self.service_providers = self._model.ServiceProviders()
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 279, in __init__
    country_code, provider_name, plan_idx = self._get_initial_config()
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 332, in _get_initial_config
    provider_name = provider_name.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'